server:
  port: 9090
  servlet:
    context-path: /



spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/datacollection?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=CTT
    username: root
    password: 123


  thymeleaf:
    cache: false

  # 字符编码过滤器
  http:
    encoding:
      enabled: true
      force: true
      charset: UTF-8